Repository Kernel360-cell1/algorithm-study, pull requests merged in 2024-03, with the labels that each got.

#121 feat : 10주차 - 윤선
  yoonseon/lee/BOJ_ATM.java
  yoonseon/lee/BOJ_주식.java
Labels: 고병룡

#133 feat: 이슈 생성 자동화
  .github/AUTO_ISSUE_GENERATOR.yml
  main.py
  requirements.txt
Labels: 알고리즘보단알코올

#135 refactor: workflows 폴더 변경,,
  .github/workflows/AUTO_ISSUE_GENERATOR.yml
Labels: bongeunsa

#128 feat : 11주차 - 예진
  yejin/song/BOJ_로프.java
  yejin/song/BOJ_신입사원.java
Labels: bongeunsa
